services:
  - type: web
    name: barefund
    env: php
    plan: free
    region: singapore

    buildCommand: |
      cd files
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan config:cache
      php artisan migrate --force || true
      php artisan storage:link || true

    startCommand: |
      cd files
      php artisan serve --host 0.0.0.0 --port 10000

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://barefund.onrender.com

      # DB config (replace with actual DB service values)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d14qfpa4d50c73ckhv2g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: barefunddb
      - key: DB_USERNAME
        value: barefunddb_user
      - key: DB_PASSWORD
        value: JKzhBZ9RAya90PQEfEAxyUDLkjaTAnDE

      # Mail config
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mail.tdevs.co
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: noreply@tdevs.co
      - key: MAIL_PASSWORD
        value: YOUR_EMAIL_PASSWORD
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: noreply@tdevs.co
      - key: MAIL_FROM_NAME
        value: Hyiprio
